stages:
  - build
  - test
  - push
  - deploy

variables:
  BACKEND_IMAGE: $DOCKERHUB_USER/ems-backend
  FRONTEND_IMAGE: $DOCKERHUB_USER/ems-frontend

# 🔨 BUILD
build_job:
  stage: build
  script:
    - docker build -t $BACKEND_IMAGE:latest ./EMS-Project-Backend
    - docker build -t $FRONTEND_IMAGE:latest ./EMS-Project-Frontend
  tags:
    - dev

# 🧪 TEST
test_job:
  stage: test
  script:
    - docker run --rm $BACKEND_IMAGE:latest node -e "console.log('Backend OK')"
    - docker run --rm $FRONTEND_IMAGE:latest sh -c "echo Frontend OK"
  tags:
    - dev

# 📦 PUSH
push_job:
  stage: push
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker push $BACKEND_IMAGE:latest
    - docker push $FRONTEND_IMAGE:latest
  tags:
    - dev

# 🚀 DEPLOY
deploy_job:
  stage: deploy
  script:
    - docker-compose down || true
    - docker-compose pull
    - docker-compose up -d
  tags:
    - dev