services:
  frontend:
    image: ritishhire/ems-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: ritishhire/ems-backend:latest
    ports:
      - "6000:6000"
    environment:
      MONGO_URI: mongodb://mongo:27017/erpppppp
      JWT_SECRET: ritish_secret
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: